name: novita
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  disk_space_plus: ^0.2.6
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.3
  table_calendar: ^3.1.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.0

# Splash Screen Configuration
flutter_native_splash:
  color: "#6C4CF5"
  color_dark: "#1C1C1E"

flutter:
  uses-material-design: true

  assets:
    - assets/
