name: novita
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.1+7

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # Firebase
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.0

  # Authentication & Network
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.2.1

  # UI Components
  flutter_native_splash: ^2.4.1
  flutter_staggered_grid_view: ^0.7.0
  table_calendar: ^3.1.2

  # Utilities
  disk_space_plus: ^0.2.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generators
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.0

  # Lints
  flutter_lints: ^5.0.0

# Splash Screen Configuration
flutter_native_splash:
  color: "#6C4CF5"
  color_dark: "#1C1C1E"

flutter:
  uses-material-design: true

  assets:
    - assets/
