name: novita
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management & DB
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # Image Picker
  image_picker: ^1.1.2
  
  # Unique ID
  uuid: ^4.4.0

  # Firebase
  firebase_core: ^3.1.1
  firebase_analytics: ^11.1.0
  firebase_crashlytics: ^4.0.0

  # Formatting
  intl: ^0.19.0

  # App Info
  package_info_plus: ^8.0.0
  disk_space_plus: ^0.2.6 # Corrected version

  # Typography
  google_fonts: ^6.2.1

  # Native Splash Screen
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generators
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1

# Splash Screen Configuration
flutter_native_splash:
  color: "#6C4CF5"
  color_dark: "#1C1C1E"

flutter:
  uses-material-design: true

  assets:
    - assets/
